-- 코드를 입력하세요
SELECT A.AUTHOR_ID AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM AUTHOR A, (SELECT AUTHOR_ID, CATEGORY, SUM(price*sales) TOTAL_SALES 
                FROM BOOK B, BOOK_SALES BS 
                WHERE B.BOOK_ID = BS.BOOK_ID 
                AND TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
                GROUP BY AUTHOR_ID, CATEGORY) B
WHERE A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC;