-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
WHERE R.FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO WHERE FOOD_TYPE = R.FOOD_TYPE)
ORDER BY R.FOOD_TYPE DESC;