-- 코드를 입력하세요
SELECT B.CATEGORY AS CATEGORY, SUM(BS.SALES)
FROM BOOK B, BOOK_SALES BS
WHERE
B.BOOK_ID = BS.BOOK_ID
AND
TO_CHAR(BS.SALES_DATE,'YYYY-MM') LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;